### ISSUE TITLE
the default port number bombs

### ISSUE THREAD

**Issue by matecsaj** [asyncapi/python-paho-template#103]
#### Describe the bug

In messaging.py the following line fails when the configure file has a blank port.
port = int(config.get('port', '1883'))

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

1. run ag https://developer.ebay.com/cms/files/asyncapi/marketplace_account_deletion.yaml @asyncapi/python-paho-template -o notification-endpoint
2. in directory notification-endpoint copy config-template.ini to config.ini
3. in directory notification-endpoint run main.py
4. observe that the program crashes because an empty string can't be converted to an int

- Screenshots

/usr/local/bin/python3.8 /Users/matecsaj/Documents/Projects/Nugget/ebay_asynch/notification-endpoint/main.py
INFO:root:Start of main.
Traceback (most recent call last):
  File "/Users/matecsaj/Documents/Projects/Nugget/ebay_asynch/notification-endpoint/main.py", line 41, in <module>
    main()
  File "/Users/matecsaj/Documents/Projects/Nugget/ebay_asynch/notification-endpoint/main.py", line 29, in main
    marketplaceAccountDeletionMessenger = messaging.Messaging(config)
  File "/Users/matecsaj/Documents/Projects/Nugget/ebay_asynch/notification-endpoint/messaging.py", line 35, in __init__
    port = int(config.get('port', '1883'))
ValueError: invalid literal for int() with base 10: ''

Process finished with exit code 1

- Link to GitHub repository with the project that has issues
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)

#### Expected behaviour

IMHO a line with a blank port should be treated the same as if the port line is absent. A suggestion for achieving that follows.

port = config.get('port')
port = int(port) if port else 1833

**Comment by derberg** [comment]
@matecsaj please go ahead and open up a PR

**Comment by matecsaj** [comment]
A PR for this was submitted months ago and the PR is awaiting approval or comment from the repo owner.
