### ISSUE TITLE
Failing to process Compliant AsyncAPI Document - Component/Schema Failure

### ISSUE THREAD

**Issue by Paul-T-AU** [asyncapi/python-paho-template#4]
#### Describe the bug

When trying to generate classes from a compliant sample without a seperate defined schema the generator fails with following error.

Error: Unable to call `the return value of (asyncapi["components"])["schemas"]

#### How to Reproduce

Failure can be seen when trying to process Streetlights tutorial.

asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt

channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.

#### Expected behavior

AsyncAPI 2.0 compliant files should be processed correctly.

**Comment by damaru-inc** [comment]
Sorry I missed this one, I'll look at it over the next few days.
