### ISSUE TITLE
Variable is already declared in the upper scope

### ISSUE THREAD

**Issue by derberg** [asyncapi/python-paho-template#80]
Happens 4 times in `filters/all.js`

- https://sonarcloud.io/project/issues?id=asyncapi_python-paho-template&issues=AXh_ZoW4keCJKpTw9hZS&open=AXh_ZoW4keCJKpTw9hZS
- https://sonarcloud.io/project/issues?id=asyncapi_python-paho-template&issues=AXSXXDAO84R5FJpcqEfG&open=AXSXXDAO84R5FJpcqEfG
- https://sonarcloud.io/project/issues?id=asyncapi_python-paho-template&issues=AXSXXDAO84R5FJpcqEfJ&open=AXSXXDAO84R5FJpcqEfJ
- https://sonarcloud.io/project/issues?id=asyncapi_python-paho-template&issues=AXSXXDAO84R5FJpcqEfL&open=AXSXXDAO84R5FJpcqEfL

**Comment by MOHAMMADArsalan** [comment]
@derberg Can i take this issue?

**Comment by derberg** [comment]
Go ahead please!
